In [2]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [4]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [5]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [6]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus: \n", salaries_with_bonus)


Salaries after bonus: 
 [[ 55  70  85]
 [ 85 100 115]]


In [7]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [8]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [12]:
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data: \n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data: 
     X   Y   Z
0  23  19  35
1   4  22  33
2  41  40  20
3  33  19  14
4  26  42  32
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  23  19  35  3.135494  4.358899
1   4  22  33  1.386294  4.690416
2  41  40  20  3.713572  6.324555
3  33  19  14  3.496508  4.358899
4  26  42  32  3.258097  6.480741
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.432352 -0.688453  0.959628  0.420086
Y       0.432352  1.000000 -0.010719  0.375998  0.999735
Z      -0.688453 -0.010719  1.000000 -0.545912 -0.007010
Log_X   0.959628  0.375998 -0.545912  1.000000  0.358931
Sqrt_Y  0.420086  0.999735 -0.007010  0.358931  1.000000


In [13]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame: \n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame: 
     X   Y   Z     Log_X    Sqrt_Y
0  23  19  35  3.135494  4.358899
1   4  22  33  1.386294  4.690416
2  41  40  20  3.713572  6.324555
3  33  19  14  3.496508  4.358899
4  26  42  32  3.258097  6.480741
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   25.400000  28.400000  26.800000  2.997993  5.242702
std    13.831124  11.588788   9.257429  0.927996  1.068923
min     4.000000  19.000000  14.000000  1.386294  4.358899
25%    23.000000  19.000000  20.000000  3.135494  4.358899
50%    26.000000  22.000000  32.000000  3.258097  4.690416
75%    33.000000  40.000000  33.000000  3.496508  6.324555
max    41.000000  42.000000  35.000000  3.713572  6.480741
Column Means:
 X         25.400000
Y         28.400000
Z         26.800000
Log_X      2.997993
Sqrt_Y     5.242702
dtype: float64
Column Standard Deviations:
 X         13.831124
Y         

In [16]:
import os
print(os.getcwd())

c:\Users\SeanCyruz\Lab6_Numerical_Data_Pido


In [2]:
import pandas as pd
import numpy as np

In [6]:
# Updated Step 2: Ensure the column names match the 2023 dataset
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

Subset of Data:
                     Country                                       EdLevel  \
0                       NaN                                           NaN   
1  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4               Philippines  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro  ConvertedCompYearly  
0          NaN                  NaN  
1            9             285000.0  
2           23             250000.0  
3            7             156000.0  
4            4              23456.0  


In [8]:
# Change 'ConvertedComp' to 'ConvertedCompYearly'
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

In [13]:
import pandas as pd
import numpy as np

In [17]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df_kaggle = pd.read_csv('survey_results_public.csv')

# Step 2: Select relevant columns
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# --- FIX FOR TYPEERROR ---
# This converts text like 'Less than 1 year' to numbers so np.where works
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna() 

# Step 4: Categorize experience
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group and compute average
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

# Step 6: Reset index and print
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Formatted Grouped Data:
        Country ExperienceLevel  ConvertedCompYearly
0  Afghanistan          Junior         1.031035e+06
1  Afghanistan          Senior         3.300000e+01
2      Albania          Junior         2.564647e+04
3      Albania          Senior         1.397000e+05
4      Algeria          Junior         9.103895e+03


In [19]:
import numpy as np
import pandas as pd

STUDENT_NAME = "PIDO"

STUDENT_ID = 255526

In [20]:
# 1: 1D Array Statistics
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

PIDO's Array: [52 37 64 32 20 34 32 65 46 38]
Mean: 42.0 Std Dev: 13.849187701811251


In [22]:
# 2: Row and Column Sums
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

PIDO's Matrix:
 [[26 37 32 20]
 [34 32  1 20]
 [18 44 38 11]]
Row sums: [115  87 111]
Column sums: [ 78 113  71  51]


In [23]:
# 3: 3D Array Slicing
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

PIDO's 3D Array:
 [[[ 9  3  5]
  [ 4 15 15]
  [ 3  1 15]]

 [[ 0  3  1]
  [14 11 13]
  [ 5 15 10]]

 [[ 6 12 12]
  [ 5  2  4]
  [ 6  2  7]]]
Slice[:,1,:]:
 [[ 4 15 15]
 [14 11 13]
 [ 5  2  4]]


In [24]:
# 4: Boolean Filtering
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

PIDO's Original: [52 37 64 32 20 34 32 65 46 38]
Filtered subset: []


In [25]:
# 5: Matrix Multiplication
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
product = A @ B
det_A = np.linalg.det(A)
print(f"{STUDENT_NAME}'s A @ B:\n", product)
print("Determinant of A:", det_A)

PIDO's A @ B:
 [[ 921 1572]
 [1108 1424]]
Determinant of A: -664.0000000000005


In [26]:
# 6: Trigonometric Functions
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

PIDO's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [27]:
# 7: Slicing with Steps
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

PIDO's Modified 4x4 Array:
 [[ 0 37  0 20]
 [34 32  1 20]
 [ 0 44  0 11]
 [ 7 29 45 22]]


In [28]:
# 8: Pass/Fail Logic (np.where)
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

PIDO's Scores: [51 36 63 31 19 33 31 64 45 37]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [29]:
# 9: Shape Manipulation
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Flattened:", arr.flatten())
print("Transposed:\n", arr.T)

PIDO's Flattened: [26 37 32 20 34 32  1 20 18 44 38 11]
Transposed:
 [[26 34 18]
 [37 32 44]
 [32  1 38]
 [20 20 11]]


In [30]:
# 10: Even/Odd Masking
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print(f"{STUDENT_NAME}'s Conditional Array:\n", arr)

PIDO's Conditional Array:
 [[-1 37 -1]
 [-1 -1 -1]
 [ 1 -1 -1]]


In [31]:
# 11: DataFrame Creation
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

   Name  Score  YearsCodePro
0  PIDO     51            15
1  PIDO     62             0
2  PIDO     57             3
3  PIDO     45             1
4  PIDO     59            14


In [32]:
# 12: Grouped Salary Averages
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
print(df.groupby('EdLevel')['ConvertedComp'].mean())

EdLevel
Bachelor    127929.0
Master      124555.0
PhD          43108.0
Name: ConvertedComp, dtype: float64


In [34]:
# 13: Sorting Values
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
print(df.sort_values(by='ConvertedComp', ascending=False))

       Country  ConvertedComp
4      Germany         147553
0  Philippines         133619
3       Canada         122239
1          USA         101557
2           UK          43108


In [35]:
# 14: Experience Filter
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name':[STUDENT_NAME]*5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df[df['YearsCodePro'] > STUDENT_ID % 10])

   Name  YearsCodePro
0  PIDO             9
4  PIDO            15


In [36]:
# 15: Bracket Binning
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         133619  100-150k
1         101557  100-150k
2          43108     0-50k
3         122239  100-150k
4         147553  100-150k


In [37]:
# 16: Logarithmic Scaling
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         133619  11.802748
1         101557  11.528375
2          43108  10.671464
3         122239  11.713733
4         147553  11.901943


In [39]:
# 17: Correlation Matrices
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
print(df.corr())

               YearsCodePro  ConvertedComp
YearsCodePro         1.0000        -0.2105
ConvertedComp       -0.2105         1.0000


In [40]:
# 18: Multiple Aggregations
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor  127929.0  127929.0   8046.875170
1    Master  124555.0  124555.0  32524.083507
2       PhD   43108.0   43108.0           NaN


In [41]:
# 19: High Pay Classification
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['HighPay'] = np.where(df['ConvertedComp'] > 110000, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0         133619     Yes
1         101557      No
2          43108      No
3         122239     Yes
4         147553     Yes


In [42]:
# 20: Country Max/Mean Summary
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
print(df.groupby('Country')['ConvertedComp'].agg(['mean','max']))

                 mean     max
Country                      
Canada       122239.0  122239
Germany      147553.0  147553
Philippines  133619.0  133619
UK            43108.0   43108
USA          101557.0  101557


In [43]:
try:
    a = np.array([1,2,3])
    b = np.array([[1], [2], [3]])
    result = a + b
    print(result)
except ValueError as e:
    print(f"Broadcasting error: {e}")

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [44]:
identity = np.eye(3)
matrix = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
print("Matrix + Identity:\n", matrix + identity)

Matrix + Identity:
 [[ 3.  3.  4.]
 [ 1.  1.  6.]
 [ 7.  8. 10.]]


In [46]:
import numpy as np
import pandas as pd

# Detecting NaNs and Invalid Data in Arrays (NumPy)
# This removes np.nan (Not a Number) and np.inf (Infinite) values
data = np.array([1, 2, np.nan, 4, np.inf])
cleaned = data[np.isfinite(data)] 
print("Cleaned NumPy Data:", cleaned)

# Handling Missing Data in Pandas
# dropna() removes rows containing None or NaN values
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None], 
    "Score": [85, None, 92, 88]
})
df_cleaned = df.dropna()
print("\nCleaned DataFrame:\n", df_cleaned)

Cleaned NumPy Data: [1. 2. 4.]

Cleaned DataFrame:
       Name  Score
0    Alice   85.0
2  Charlie   92.0
